// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.4
// source: shipment.proto

package shipment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShipmentRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ReferenceNumber       string                 `protobuf:"bytes,1,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	Origin                string                 `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination           string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	DriverName            string                 `protobuf:"bytes,4,opt,name=driver_name,json=driverName,proto3" json:"driver_name,omitempty"`
	DriverPhone           string                 `protobuf:"bytes,5,opt,name=driver_phone,json=driverPhone,proto3" json:"driver_phone,omitempty"`
	UnitNumber            string                 `protobuf:"bytes,6,opt,name=unit_number,json=unitNumber,proto3" json:"unit_number,omitempty"`
	ShipmentAmount        float64                `protobuf:"fixed64,7,opt,name=shipment_amount,json=shipmentAmount,proto3" json:"shipment_amount,omitempty"`
	ShipmentCurrency      string                 `protobuf:"bytes,8,opt,name=shipment_currency,json=shipmentCurrency,proto3" json:"shipment_currency,omitempty"`
	DriverRevenue         float64                `protobuf:"fixed64,9,opt,name=driver_revenue,json=driverRevenue,proto3" json:"driver_revenue,omitempty"`
	DriverRevenueCurrency string                 `protobuf:"bytes,10,opt,name=driver_revenue_currency,json=driverRevenueCurrency,proto3" json:"driver_revenue_currency,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateShipmentRequest) Reset() {
	*x = CreateShipmentRequest{}
	mi := &file_shipment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentRequest) ProtoMessage() {}

func (x *CreateShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentRequest.ProtoReflect.Descriptor instead.
func (*CreateShipmentRequest) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShipmentRequest) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *CreateShipmentRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *CreateShipmentRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *CreateShipmentRequest) GetDriverName() string {
	if x != nil {
		return x.DriverName
	}
	return ""
}

func (x *CreateShipmentRequest) GetDriverPhone() string {
	if x != nil {
		return x.DriverPhone
	}
	return ""
}

func (x *CreateShipmentRequest) GetUnitNumber() string {
	if x != nil {
		return x.UnitNumber
	}
	return ""
}

func (x *CreateShipmentRequest) GetShipmentAmount() float64 {
	if x != nil {
		return x.ShipmentAmount
	}
	return 0
}

func (x *CreateShipmentRequest) GetShipmentCurrency() string {
	if x != nil {
		return x.ShipmentCurrency
	}
	return ""
}

func (x *CreateShipmentRequest) GetDriverRevenue() float64 {
	if x != nil {
		return x.DriverRevenue
	}
	return 0
}

func (x *CreateShipmentRequest) GetDriverRevenueCurrency() string {
	if x != nil {
		return x.DriverRevenueCurrency
	}
	return ""
}

type CreateShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipment      *Shipment              `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShipmentResponse) Reset() {
	*x = CreateShipmentResponse{}
	mi := &file_shipment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentResponse) ProtoMessage() {}

func (x *CreateShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentResponse.ProtoReflect.Descriptor instead.
func (*CreateShipmentResponse) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShipmentResponse) GetShipment() *Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

type GetShipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentRequest) Reset() {
	*x = GetShipmentRequest{}
	mi := &file_shipment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentRequest) ProtoMessage() {}

func (x *GetShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentRequest.ProtoReflect.Descriptor instead.
func (*GetShipmentRequest) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{2}
}

func (x *GetShipmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipment      *Shipment              `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentResponse) Reset() {
	*x = GetShipmentResponse{}
	mi := &file_shipment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentResponse) ProtoMessage() {}

func (x *GetShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentResponse.ProtoReflect.Descriptor instead.
func (*GetShipmentResponse) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{3}
}

func (x *GetShipmentResponse) GetShipment() *Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId    string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Notes         string                 `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_shipment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateStatusRequest) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *UpdateStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateStatusRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateStatusRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type UpdateStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *StatusEvent           `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusResponse) Reset() {
	*x = UpdateStatusResponse{}
	mi := &file_shipment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusResponse) ProtoMessage() {}

func (x *UpdateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateStatusResponse) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateStatusResponse) GetEvent() *StatusEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type GetEventHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId    string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventHistoryRequest) Reset() {
	*x = GetEventHistoryRequest{}
	mi := &file_shipment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventHistoryRequest) ProtoMessage() {}

func (x *GetEventHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetEventHistoryRequest) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{6}
}

func (x *GetEventHistoryRequest) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

type GetEventHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*StatusEvent         `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventHistoryResponse) Reset() {
	*x = GetEventHistoryResponse{}
	mi := &file_shipment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventHistoryResponse) ProtoMessage() {}

func (x *GetEventHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetEventHistoryResponse) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{7}
}

func (x *GetEventHistoryResponse) GetEvents() []*StatusEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type Shipment struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReferenceNumber       string                 `protobuf:"bytes,2,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	Origin                string                 `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination           string                 `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	Status                string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	DriverName            string                 `protobuf:"bytes,6,opt,name=driver_name,json=driverName,proto3" json:"driver_name,omitempty"`
	DriverPhone           string                 `protobuf:"bytes,7,opt,name=driver_phone,json=driverPhone,proto3" json:"driver_phone,omitempty"`
	UnitNumber            string                 `protobuf:"bytes,8,opt,name=unit_number,json=unitNumber,proto3" json:"unit_number,omitempty"`
	ShipmentAmount        float64                `protobuf:"fixed64,9,opt,name=shipment_amount,json=shipmentAmount,proto3" json:"shipment_amount,omitempty"`
	ShipmentCurrency      string                 `protobuf:"bytes,10,opt,name=shipment_currency,json=shipmentCurrency,proto3" json:"shipment_currency,omitempty"`
	DriverRevenue         float64                `protobuf:"fixed64,11,opt,name=driver_revenue,json=driverRevenue,proto3" json:"driver_revenue,omitempty"`
	DriverRevenueCurrency string                 `protobuf:"bytes,12,opt,name=driver_revenue_currency,json=driverRevenueCurrency,proto3" json:"driver_revenue_currency,omitempty"`
	CreatedAt             *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Shipment) Reset() {
	*x = Shipment{}
	mi := &file_shipment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shipment) ProtoMessage() {}

func (x *Shipment) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shipment.ProtoReflect.Descriptor instead.
func (*Shipment) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{8}
}

func (x *Shipment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Shipment) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *Shipment) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Shipment) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Shipment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Shipment) GetDriverName() string {
	if x != nil {
		return x.DriverName
	}
	return ""
}

func (x *Shipment) GetDriverPhone() string {
	if x != nil {
		return x.DriverPhone
	}
	return ""
}

func (x *Shipment) GetUnitNumber() string {
	if x != nil {
		return x.UnitNumber
	}
	return ""
}

func (x *Shipment) GetShipmentAmount() float64 {
	if x != nil {
		return x.ShipmentAmount
	}
	return 0
}

func (x *Shipment) GetShipmentCurrency() string {
	if x != nil {
		return x.ShipmentCurrency
	}
	return ""
}

func (x *Shipment) GetDriverRevenue() float64 {
	if x != nil {
		return x.DriverRevenue
	}
	return 0
}

func (x *Shipment) GetDriverRevenueCurrency() string {
	if x != nil {
		return x.DriverRevenueCurrency
	}
	return ""
}

func (x *Shipment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Shipment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type StatusEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShipmentId    string                 `protobuf:"bytes,2,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Notes         string                 `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusEvent) Reset() {
	*x = StatusEvent{}
	mi := &file_shipment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusEvent) ProtoMessage() {}

func (x *StatusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusEvent.ProtoReflect.Descriptor instead.
func (*StatusEvent) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{9}
}

func (x *StatusEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StatusEvent) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *StatusEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusEvent) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *StatusEvent) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *StatusEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_shipment_proto protoreflect.FileDescriptor

const file_shipment_proto_rawDesc = "" +
	"\n" +
	"\x0eshipment.proto\x12\bshipment\x1a\x1fgoogle/protobuf/timestamp.proto\"\x96\x03\n" +
	"\x15CreateShipmentRequest\x12)\n" +
	"\x10reference_number\x18\x01 \x01(\tR\x0freferenceNumber\x12\x16\n" +
	"\x06origin\x18\x02 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12\x1f\n" +
	"\vdriver_name\x18\x04 \x01(\tR\n" +
	"driverName\x12!\n" +
	"\fdriver_phone\x18\x05 \x01(\tR\vdriverPhone\x12\x1f\n" +
	"\vunit_number\x18\x06 \x01(\tR\n" +
	"unitNumber\x12'\n" +
	"\x0fshipment_amount\x18\a \x01(\x01R\x0eshipmentAmount\x12+\n" +
	"\x11shipment_currency\x18\b \x01(\tR\x10shipmentCurrency\x12%\n" +
	"\x0edriver_revenue\x18\t \x01(\x01R\rdriverRevenue\x126\n" +
	"\x17driver_revenue_currency\x18\n" +
	" \x01(\tR\x15driverRevenueCurrency\"H\n" +
	"\x16CreateShipmentResponse\x12.\n" +
	"\bshipment\x18\x01 \x01(\v2\x12.shipment.ShipmentR\bshipment\"$\n" +
	"\x12GetShipmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x13GetShipmentResponse\x12.\n" +
	"\bshipment\x18\x01 \x01(\v2\x12.shipment.ShipmentR\bshipment\"\x80\x01\n" +
	"\x13UpdateStatusRequest\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x14\n" +
	"\x05notes\x18\x04 \x01(\tR\x05notes\"C\n" +
	"\x14UpdateStatusResponse\x12+\n" +
	"\x05event\x18\x01 \x01(\v2\x15.shipment.StatusEventR\x05event\"9\n" +
	"\x16GetEventHistoryRequest\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\"H\n" +
	"\x17GetEventHistoryResponse\x12-\n" +
	"\x06events\x18\x01 \x03(\v2\x15.shipment.StatusEventR\x06events\"\xa7\x04\n" +
	"\bShipment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10reference_number\x18\x02 \x01(\tR\x0freferenceNumber\x12\x16\n" +
	"\x06origin\x18\x03 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x04 \x01(\tR\vdestination\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1f\n" +
	"\vdriver_name\x18\x06 \x01(\tR\n" +
	"driverName\x12!\n" +
	"\fdriver_phone\x18\a \x01(\tR\vdriverPhone\x12\x1f\n" +
	"\vunit_number\x18\b \x01(\tR\n" +
	"unitNumber\x12'\n" +
	"\x0fshipment_amount\x18\t \x01(\x01R\x0eshipmentAmount\x12+\n" +
	"\x11shipment_currency\x18\n" +
	" \x01(\tR\x10shipmentCurrency\x12%\n" +
	"\x0edriver_revenue\x18\v \x01(\x01R\rdriverRevenue\x126\n" +
	"\x17driver_revenue_currency\x18\f \x01(\tR\x15driverRevenueCurrency\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc3\x01\n" +
	"\vStatusEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vshipment_id\x18\x02 \x01(\tR\n" +
	"shipmentId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x14\n" +
	"\x05notes\x18\x05 \x01(\tR\x05notes\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xd9\x02\n" +
	"\x0fShipmentService\x12S\n" +
	"\x0eCreateShipment\x12\x1f.shipment.CreateShipmentRequest\x1a .shipment.CreateShipmentResponse\x12J\n" +
	"\vGetShipment\x12\x1c.shipment.GetShipmentRequest\x1a\x1d.shipment.GetShipmentResponse\x12M\n" +
	"\fUpdateStatus\x12\x1d.shipment.UpdateStatusRequest\x1a\x1e.shipment.UpdateStatusResponse\x12V\n" +
	"\x0fGetEventHistory\x12 .shipment.GetEventHistoryRequest\x1a!.shipment.GetEventHistoryResponseB4Z2github.com/victus-est-deus/shipment/proto/shipmentb\x06proto3"

var (
	file_shipment_proto_rawDescOnce sync.Once
	file_shipment_proto_rawDescData []byte
)

func file_shipment_proto_rawDescGZIP() []byte {
	file_shipment_proto_rawDescOnce.Do(func() {
		file_shipment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shipment_proto_rawDesc), len(file_shipment_proto_rawDesc)))
	})
	return file_shipment_proto_rawDescData
}

var file_shipment_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_shipment_proto_goTypes = []any{
	(*CreateShipmentRequest)(nil),   // 0: shipment.CreateShipmentRequest
	(*CreateShipmentResponse)(nil),  // 1: shipment.CreateShipmentResponse
	(*GetShipmentRequest)(nil),      // 2: shipment.GetShipmentRequest
	(*GetShipmentResponse)(nil),     // 3: shipment.GetShipmentResponse
	(*UpdateStatusRequest)(nil),     // 4: shipment.UpdateStatusRequest
	(*UpdateStatusResponse)(nil),    // 5: shipment.UpdateStatusResponse
	(*GetEventHistoryRequest)(nil),  // 6: shipment.GetEventHistoryRequest
	(*GetEventHistoryResponse)(nil), // 7: shipment.GetEventHistoryResponse
	(*Shipment)(nil),                // 8: shipment.Shipment
	(*StatusEvent)(nil),             // 9: shipment.StatusEvent
	(*timestamppb.Timestamp)(nil),   // 10: google.protobuf.Timestamp
}
var file_shipment_proto_depIdxs = []int32{
	8,  // 0: shipment.CreateShipmentResponse.shipment:type_name -> shipment.Shipment
	8,  // 1: shipment.GetShipmentResponse.shipment:type_name -> shipment.Shipment
	9,  // 2: shipment.UpdateStatusResponse.event:type_name -> shipment.StatusEvent
	9,  // 3: shipment.GetEventHistoryResponse.events:type_name -> shipment.StatusEvent
	10, // 4: shipment.Shipment.created_at:type_name -> google.protobuf.Timestamp
	10, // 5: shipment.Shipment.updated_at:type_name -> google.protobuf.Timestamp
	10, // 6: shipment.StatusEvent.created_at:type_name -> google.protobuf.Timestamp
	0,  // 7: shipment.ShipmentService.CreateShipment:input_type -> shipment.CreateShipmentRequest
	2,  // 8: shipment.ShipmentService.GetShipment:input_type -> shipment.GetShipmentRequest
	4,  // 9: shipment.ShipmentService.UpdateStatus:input_type -> shipment.UpdateStatusRequest
	6,  // 10: shipment.ShipmentService.GetEventHistory:input_type -> shipment.GetEventHistoryRequest
	1,  // 11: shipment.ShipmentService.CreateShipment:output_type -> shipment.CreateShipmentResponse
	3,  // 12: shipment.ShipmentService.GetShipment:output_type -> shipment.GetShipmentResponse
	5,  // 13: shipment.ShipmentService.UpdateStatus:output_type -> shipment.UpdateStatusResponse
	7,  // 14: shipment.ShipmentService.GetEventHistory:output_type -> shipment.GetEventHistoryResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_shipment_proto_init() }
func file_shipment_proto_init() {
	if File_shipment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shipment_proto_rawDesc), len(file_shipment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shipment_proto_goTypes,
		DependencyIndexes: file_shipment_proto_depIdxs,
		MessageInfos:      file_shipment_proto_msgTypes,
	}.Build()
	File_shipment_proto = out.File
	file_shipment_proto_goTypes = nil
	file_shipment_proto_depIdxs = nil
}
